name: DimensionTeleporter
author: RoboMWM
version: ${project.version}
main: me.robomwm.DimensionTeleporter.Main
commands:
   dt:
      description: Teleport to a dimension or loaded world.
      usage: /dt <world name>
      permission: dimensionteleporter.dt
      permission-message: You don't have DimensionTeleporter.dt
   dtp:
      description: Teleport to a dimension or loaded world.
      usage: /dtp <world name> <player>
      permission: dimensionteleporter.dtp
      permission-message: You don't have DimensionTeleporter.dtp
permissions:
    dimensionteleporter.*:
        description: Grants ALL THE THINGS
        children:
            DimensionTeleporter.dt: true
            DimensionTeleporter.dtp: true
    dimensionteleporter.dt:
        description: Permission to /dt
        default: op
    dimensionteleporter.dtp:
        description: Permission to /dtp
        default: op